apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: {{ .Values.dopplerSecret.name }}
  namespace: {{ .Release.Namespace }}
spec:
  tokenSecret:
    name: {{ .Values.tokenSecret.name }}
    namespace: {{ .Release.Namespace }}
  project: {{ required "doppler.project is required" .Values.doppler.project | quote }}
  config: {{ required "doppler.config is required" .Values.doppler.config | quote }}
  managedSecret:
    name: {{ .Values.managedSecret.name }}
    namespace: {{ required "managedSecret.namespace is required" .Values.managedSecret.namespace | quote }}
    type: Opaque
