apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aero-staging-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: aero-staging
  source:
    repoURL: git@github.com:KNehe/aero_bound_ventures.git
    targetRevision: main
    path: helm/monitoring
    helm:
      releaseName: aero-monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: grafana
      namespace: monitoring
      jsonPointers:
        - /data/admin-password
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        environment: staging
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
